name: relationships
description: Relationship modeling and kinship calculations with localized descriptions.
version: 0.0.2
repository: https://github.com/ahnaineh/relationships
issue_tracker: https://github.com/ahnaineh/relationships/issues


environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.2
  slang: ^4.11.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  freezed: ^3.2.0
  collection: ^1.19.1
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
